site_name: How To Make A Mobile Robot
theme: readthedocs

nav:
    - About: 'about.md'
    - Robot Components: 'robot-components/introduction-to-robot-components.md'
    - Robot Model: 'robot-model/README.md'
