site_name: How To Make A Mobile Robot
site_description: TODO
site_author: "TODO"
theme: material
# theme: readthedocs
#theme: litera
# theme:
#   name: "rtd-dropdown"
#   collapse_by_default: false
#   highlightjs: true
#   hljs_languages:
#     - yaml
#     - python

# The site is hosted as a static site on GitHub Pages
site_url: https://multi-agent-robotics.github.io/How-to-make-a-mobile-robot/
# The repo is hosted on GitHub
repo_url: https://github.com/Multi-Agent-Robotics/How-to-make-a-mobile-robot

nav:
  - Building the Robot:
    - Introduction: build/index.md
    - Components: build/components/components.md
    - Model: build/model/model.md
    - Assembly: build/assembly/assembly-steps.md
  - Hardware Setup:
    - Nvidia Jetson AGX Orin: hardware/nvidia-jetson-agx-orin.md
    - VESC: hardware/vesc.md
  - Software Setup:
    - ORBSLAM3: software/orbslam3.md
    - ORBSLAM3 ROS2 Wrapper: software/orbslam3-ros2-wrapper.md
    - ZED SDK ROS2 Wrapper: software/zed-sdk-ros2-wrapper.md