site_name: How To Make A Mobile Robot
site_description: TODO
site_author: "TODO"
theme: readthedocs
#theme: litera
# theme:
#   name: "rtd-dropdown"
#   collapse_by_default: false
#   highlightjs: true
#   hljs_languages:
#     - yaml
#     - python

repo_url: https://github.com/Multi-Agent-Robotics/How-to-make-a-mobile-robot

nav:
  - Introduction: "introduction.md"
  - Components: "components/components.md"
  - Model: "model/model.md"
  - Assembly: "assembly/assembly-steps.md"
  - Nvidia Jetson AGX Orin: "nvidia-jetson-agx-orin.md"
  - VESC: vesc.md
